### ISSUE TITLE
Define and Document Branching Strategy & GitVersion Configuration

### ISSUE THREAD

**Issue by MikDal002** [MikDal002/ZTR.Templates#44]
## Business Value
Ensures consistent versioning, clear development workflow, and improved collaboration by providing a well-defined branching model and automated version management. This reduces ambiguity and potential for errors in versioning and release processes.

## Description
This task involves finalizing the `GitVersion.yml` configuration and documenting the chosen branching strategy (GitFlow-like with `master`, `develop`, `feature/*`, and `hotfix/*` branches) in the project's `Readme.md`.

The proposed `GitVersion.yml` configuration to be confirmed/finalized is:
```yaml
# workflow: GitFlow # This line was in the original, confirm if it should be active
# Ensure the rest of the configuration aligns with the intended GitFlow-like process.

branches:
  master:
    tag: '' # No pre-release tag for master (e.g., 1.0.0)
    increment: Patch # Increment Patch version for each commit/merge to master
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    is-release-branch: true

  develop:
    tag: alpha # Common pre-release tag for develop builds (e.g., 1.1.0-alpha.1)
    increment: Minor # Increment Minor version on develop
    prevent-increment-of-merged-branch-version: true
    track-merge-target: true # Key for develop to advance based on master
    is-release-branch: false

  feature:
    # Matches any branch not master, develop, release, or hotfix
    regex: ^(?!(master|develop|release|hotfix)$).*
    tag: use-branch-name # Or a fixed tag like 'feat'
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    is-release-branch: false

  hotfix: # Based on the default commented-out config from original GitVersion.yml
    regex: hotfixes?[/-]
    tag: beta
    increment: Patch # Hotfixes usually increment patch on master's version
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    is-release-branch: false

# Optional: Release branches (if to be used, uncomment and configure)
#  release:
#    regex: releases?[/-]
#    tag: rc
#    increment: None
#    prevent-increment-of-merged-branch-version: true
#    track-merge-target: false
#    is-release-branch: true
```

The branching strategy needs to be clearly explained in the `Readme.md`, including how versions are generated for each branch type and a visual diagram.

## Acceptance Criteria (Gherkin Scenarios)

**Scenario 1: GitVersion Configuration Finalized**
*   `Given` the `GitVersion.yml` file exists in the repository
*   `When` the GitVersion configuration for `master`, `develop`, `feature`, and `hotfix` branches is reviewed and confirmed
*   `Then` the `GitVersion.yml` file accurately reflects the agreed-upon versioning strategy.
*   `And` the `workflow: GitFlow` line is active if GitFlow is the intended overall workflow mode for GitVersion.

**Scenario 2: Branching Strategy Documented in README**
*   `Given` a `Readme.md` file exists in the repository
*   `When` the branching strategy (including `master`, `develop`, `feature/*`, `hotfix/*` branches and their versioning) is added to the `Readme.md`
*   `Then` the `Readme.md` contains a clear and concise explanation of the branching model and how GitVersion assigns versions.

**Scenario 3: Mermaid Diagram for Visualization in README**
*   `Given` the branching strategy is documented in `Readme.md`
*   `When` a Mermaid diagram illustrating the flow of branches and versioning is added to the branching strategy section
*   `Then` the `Readme.md` includes a functional and accurate visual representation of the branching model.

## Traceability
*   Links to this issue from `Readme.md` documentation.
*   Links to `GitVersion.yml`.
